on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world ${FIRST_NAME} ${middle_name} ${Last_Name}!
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
